import { Router, type IRouter } from "express";
import healthRouter from "./health.js";
import authRouter from "./auth.js";
import schoolsRouter from "./schools.js";
import platformRouter from "./platform.js";
import studentsRouter from "./students.js";
import teachersRouter from "./teachers.js";
import classesRouter from "./classes.js";
import attendanceRouter from "./attendance.js";
import feesRouter from "./fees.js";
import noticesRouter from "./notices.js";
import eventsRouter from "./events.js";
import reviewsRouter from "./reviews.js";
import jobsRouter from "./jobs.js";
import publicRouter from "./public.js";
import aiRouter from "./ai.js";
import timetableRouter from "./timetable.js";
import examsRouter from "./exams.js";
import homeworkRouter from "./homework.js";
import leavesRouter from "./leaves.js";
import messagesRouter from "./messages.js";
import announcementsRouter from "./announcements.js";
import notificationsRouter from "./notifications.js";
import galleryRouter from "./gallery.js";
import careerRouter from "./career.js";
import platformSettingsRouter from "./platform_settings.js";
import libraryRouter from "./library.js";
import transportRouter from "./transport.js";
import payrollRouter from "./payroll.js";
import ptmRouter from "./ptm.js";
import disciplineRouter from "./discipline.js";
import studyMaterialsRouter from "./study_materials.js";
import assignmentsRouter from "./assignments.js";
import supportRouter from "./support.js";
import admissionsRouter from "./admissions.js";
import studentHealthRouter from "./student_health.js";
import studentLeavesRouter from "./student_leaves.js";
import quizzesRouter from "./quizzes.js";

const router: IRouter = Router();

router.use(healthRouter);
router.use("/auth", authRouter);
router.use("/schools", schoolsRouter);
router.use("/platform", platformRouter);
router.use("/students", studentsRouter);
router.use("/teachers", teachersRouter);
router.use("/classes", classesRouter);
router.use("/attendance", attendanceRouter);
router.use("/fees", feesRouter);
router.use("/notices", noticesRouter);
router.use("/events", eventsRouter);
router.use("/reviews", reviewsRouter);
router.use("/jobs", jobsRouter);
router.use("/public", publicRouter);
router.use("/ai", aiRouter);
router.use("/timetable", timetableRouter);
router.use("/exams", examsRouter);
router.use("/homework", homeworkRouter);
router.use("/leaves", leavesRouter);
router.use("/messages", messagesRouter);
router.use("/announcements", announcementsRouter);
router.use("/notifications", notificationsRouter);
router.use("/gallery", galleryRouter);
router.use("/career", careerRouter);
router.use("/platform/settings", platformSettingsRouter);
router.use("/library", libraryRouter);
router.use("/transport", transportRouter);
router.use("/payroll", payrollRouter);
router.use("/ptm", ptmRouter);
router.use("/discipline", disciplineRouter);
router.use("/study-materials", studyMaterialsRouter);
router.use("/assignments", assignmentsRouter);
router.use("/support", supportRouter);
router.use("/admissions", admissionsRouter);
router.use("/student-health", studentHealthRouter);
router.use("/student-leaves", studentLeavesRouter);
router.use("/quizzes", quizzesRouter);

export default router;
