import { useState, useEffect } from "react";
import { AdminLayout } from "@/components/layouts";
import { useAuth } from "@/hooks/use-auth";
import { IndianRupee, Plus, Check, Loader2, Printer, Trash2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { adminLinks } from "./admin-links";
import { useToast } from "@/hooks/use-toast";

const BASE = import.meta.env.BASE_URL.replace(/\/$/, "");
const getToken = () => localStorage.getItem("myschool_token") || "";
const MONTHS = ["January","February","March","April","May","June","July","August","September","October","November","December"];
const YEARS = [2024, 2025, 2026];

export default function Payroll() {
  const { user } = useAuth();
  const { toast } = useToast();
  const schoolId = user?.schoolId || 1;
  const [records, setRecords] = useState<any[]>([]);
  const [teachers, setTeachers] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [open, setOpen] = useState(false);
  const [filterMonth, setFilterMonth] = useState(MONTHS[new Date().getMonth()]);
  const [filterYear, setFilterYear] = useState(String(new Date().getFullYear()));
  const [form, setForm] = useState({ teacherId: "", month: MONTHS[new Date().getMonth()], year: String(new Date().getFullYear()), basicSalary: "", allowances: "0", deductions: "0", notes: "" });

  const fetchAll = async () => {
    setLoading(true);
    const [rRes, tRes] = await Promise.all([
      fetch(`${BASE}/api/payroll?schoolId=${schoolId}&month=${filterMonth}&year=${filterYear}`, { headers: { Authorization: `Bearer ${getToken()}` } }),
      fetch(`${BASE}/api/teachers?schoolId=${schoolId}`, { headers: { Authorization: `Bearer ${getToken()}` } }),
    ]);
    const [rd, td] = await Promise.all([rRes.json(), tRes.json()]);
    setRecords(rd.records || []); setTeachers(td.teachers || []);
    setLoading(false);
  };

  useEffect(() => { fetchAll(); }, [filterMonth, filterYear, schoolId]);

  const addRecord = async () => {
    const res = await fetch(`${BASE}/api/payroll`, { method: "POST", headers: { "Content-Type": "application/json", Authorization: `Bearer ${getToken()}` }, body: JSON.stringify(form) });
    if (res.ok) { toast({ title: "Payroll record created!" }); setOpen(false); fetchAll(); }
    else toast({ title: "Failed to create record", variant: "destructive" });
  };

  const markPaid = async (id: number) => {
    await fetch(`${BASE}/api/payroll/${id}/pay`, { method: "PATCH", headers: { Authorization: `Bearer ${getToken()}` } });
    toast({ title: "Marked as paid!" }); fetchAll();
  };

  const deleteRecord = async (id: number) => { await fetch(`${BASE}/api/payroll/${id}`, { method: "DELETE", headers: { Authorization: `Bearer ${getToken()}` } }); fetchAll(); };

  const printSlip = (r: any) => {
    const w = window.open("", "_blank", "width=500,height=600");
    if (!w) return;
    w.document.write(`<!DOCTYPE html><html><head><title>Payslip</title><style>body{font-family:Arial,sans-serif;padding:30px;max-width:420px;margin:auto}.header{text-align:center;margin-bottom:20px;border-bottom:2px solid #333;padding-bottom:15px}h2{margin:0}table{width:100%;border-collapse:collapse;margin:15px 0}td{padding:8px 4px;border-bottom:1px solid #eee;font-size:14px}.label{color:#666}.total{font-weight:bold;font-size:16px;border-top:2px solid #333}.footer{text-align:center;font-size:11px;color:#999;margin-top:20px}</style></head><body><div class="header"><h2>PAYSLIP</h2><p>${r.month} ${r.year}</p></div><table><tr><td class="label">Employee</td><td><b>${r.teacherName}</b></td></tr><tr><td class="label">Designation</td><td>${r.designation || "Teacher"}</td></tr><tr><td class="label">Basic Salary</td><td>₹${Number(r.basicSalary).toLocaleString("en-IN")}</td></tr><tr><td class="label">Allowances</td><td>₹${Number(r.allowances || 0).toLocaleString("en-IN")}</td></tr><tr><td class="label">Deductions</td><td>- ₹${Number(r.deductions || 0).toLocaleString("en-IN")}</td></tr><tr><td class="label total">Net Salary</td><td class="total">₹${Number(r.netSalary).toLocaleString("en-IN")}</td></tr><tr><td class="label">Status</td><td style="color:${r.status === "paid" ? "green" : "orange"};text-transform:capitalize">${r.status}</td></tr></table><div class="footer">Generated by MySchool Platform</div></body></html>`);
    w.document.close(); w.print();
  };

  const totalPaid = records.filter(r => r.status === "paid").reduce((s, r) => s + Number(r.netSalary), 0);
  const totalPending = records.filter(r => r.status !== "paid").reduce((s, r) => s + Number(r.netSalary), 0);

  return (
    <AdminLayout title="Staff Payroll" links={adminLinks}>
      <div className="grid grid-cols-3 gap-4 mb-6">
        {[{ label: "Total Staff", val: records.length, color: "bg-blue-100 text-blue-700" }, { label: "Paid", val: `₹${totalPaid.toLocaleString("en-IN")}`, color: "bg-green-100 text-green-700" }, { label: "Pending", val: `₹${totalPending.toLocaleString("en-IN")}`, color: "bg-orange-100 text-orange-700" }].map(s => (
          <Card key={s.label} className="p-4 rounded-xl text-center dark:bg-gray-800 dark:border-gray-700"><p className="text-xs text-muted-foreground mb-1">{s.label}</p><p className={`text-xl font-bold px-2 py-0.5 rounded-full inline-block ${s.color}`}>{s.val}</p></Card>
        ))}
      </div>
      <div className="flex items-center justify-between mb-4 flex-wrap gap-3">
        <div className="flex gap-2">
          <Select value={filterMonth} onValueChange={setFilterMonth}>
            <SelectTrigger className="w-36 dark:bg-gray-800 dark:border-gray-700"><SelectValue /></SelectTrigger>
            <SelectContent>{MONTHS.map(m => <SelectItem key={m} value={m}>{m}</SelectItem>)}</SelectContent>
          </Select>
          <Select value={filterYear} onValueChange={setFilterYear}>
            <SelectTrigger className="w-28 dark:bg-gray-800 dark:border-gray-700"><SelectValue /></SelectTrigger>
            <SelectContent>{YEARS.map(y => <SelectItem key={y} value={String(y)}>{y}</SelectItem>)}</SelectContent>
          </Select>
        </div>
        <Dialog open={open} onOpenChange={setOpen}>
          <DialogTrigger asChild><Button className="rounded-xl"><Plus className="w-4 h-4 mr-2" />Add Payroll</Button></DialogTrigger>
          <DialogContent className="dark:bg-gray-800 dark:border-gray-700">
            <DialogHeader><DialogTitle>Create Payroll Entry</DialogTitle></DialogHeader>
            <div className="space-y-3">
              <div><label className="text-sm font-medium dark:text-gray-300">Teacher *</label>
                <Select value={form.teacherId} onValueChange={v => setForm(p => ({ ...p, teacherId: v }))}>
                  <SelectTrigger className="dark:bg-gray-700 dark:border-gray-600"><SelectValue placeholder="Select teacher" /></SelectTrigger>
                  <SelectContent>{teachers.map(t => <SelectItem key={t.id} value={String(t.id)}>{t.name}</SelectItem>)}</SelectContent>
                </Select></div>
              <div className="grid grid-cols-2 gap-3">
                <div><label className="text-sm font-medium dark:text-gray-300">Month</label>
                  <Select value={form.month} onValueChange={v => setForm(p => ({ ...p, month: v }))}>
                    <SelectTrigger className="dark:bg-gray-700 dark:border-gray-600"><SelectValue /></SelectTrigger>
                    <SelectContent>{MONTHS.map(m => <SelectItem key={m} value={m}>{m}</SelectItem>)}</SelectContent>
                  </Select></div>
                <div><label className="text-sm font-medium dark:text-gray-300">Year</label>
                  <Select value={form.year} onValueChange={v => setForm(p => ({ ...p, year: v }))}>
                    <SelectTrigger className="dark:bg-gray-700 dark:border-gray-600"><SelectValue /></SelectTrigger>
                    <SelectContent>{YEARS.map(y => <SelectItem key={y} value={String(y)}>{y}</SelectItem>)}</SelectContent>
                  </Select></div>
              </div>
              {[["Basic Salary (₹) *", "basicSalary", "e.g. 30000"], ["Allowances (₹)", "allowances", "0"], ["Deductions (₹)", "deductions", "0"], ["Notes", "notes", "Optional remarks"]].map(([l, k, ph]) => (
                <div key={k}><label className="text-sm font-medium dark:text-gray-300">{l}</label><Input type={k.includes("Notes") ? "text" : "number"} value={(form as any)[k]} onChange={e => setForm(p => ({ ...p, [k]: e.target.value }))} placeholder={ph} className="dark:bg-gray-700 dark:border-gray-600" /></div>
              ))}
              <p className="text-sm font-bold text-primary">Net: ₹{(Number(form.basicSalary || 0) + Number(form.allowances || 0) - Number(form.deductions || 0)).toLocaleString("en-IN")}</p>
              <Button onClick={addRecord} className="w-full">Create Payroll Entry</Button>
            </div>
          </DialogContent>
        </Dialog>
      </div>
      {loading ? <div className="flex justify-center py-16"><Loader2 className="w-8 h-8 animate-spin text-primary" /></div>
      : records.length === 0 ? <div className="text-center py-16 text-muted-foreground"><IndianRupee className="w-12 h-12 mx-auto mb-3 opacity-20" /><p className="font-bold">No payroll records for {filterMonth} {filterYear}</p></div>
      : <div className="space-y-3">
          {records.map(r => (
            <Card key={r.id} className="p-4 rounded-xl dark:bg-gray-800 dark:border-gray-700">
              <div className="flex items-center justify-between gap-4">
                <div>
                  <p className="font-bold dark:text-white">{r.teacherName}</p>
                  <p className="text-sm text-muted-foreground">{r.designation || "Teacher"} • {r.month} {r.year}</p>
                  <p className="text-xs text-muted-foreground">Basic: ₹{Number(r.basicSalary).toLocaleString("en-IN")} + ₹{Number(r.allowances || 0).toLocaleString("en-IN")} - ₹{Number(r.deductions || 0).toLocaleString("en-IN")}</p>
                </div>
                <div className="flex items-center gap-2 shrink-0">
                  <p className="font-bold text-lg dark:text-white">₹{Number(r.netSalary).toLocaleString("en-IN")}</p>
                  <Badge className={`text-xs rounded-full capitalize ${r.status === "paid" ? "bg-green-100 text-green-700" : r.status === "hold" ? "bg-red-100 text-red-700" : "bg-orange-100 text-orange-700"}`}>{r.status}</Badge>
                  <Button size="sm" variant="ghost" onClick={() => printSlip(r)} className="p-1"><Printer className="w-4 h-4" /></Button>
                  {r.status !== "paid" && <Button size="sm" className="rounded-lg h-8 text-xs bg-green-600 hover:bg-green-700 text-white" onClick={() => markPaid(r.id)}><Check className="w-3 h-3 mr-1" />Pay</Button>}
                  <button onClick={() => deleteRecord(r.id)} className="text-red-400 hover:text-red-600"><Trash2 className="w-4 h-4" /></button>
                </div>
              </div>
            </Card>
          ))}
        </div>}
    </AdminLayout>
  );
}
