kind = "web"
previewPath = "/"
title = "MySchool"
version = "1.0.0"
id = "artifacts/myschool"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 19910

[services.development]
run = "pnpm --filter @workspace/myschool run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/myschool", "run", "build" ]
publicDir = "artifacts/myschool/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "19910"
BASE_PATH = "/"
